export const iconsImport = {
	tomeDamage: new URL('./tomeDamage.svg', import.meta.url).href,
	tomeCooldown: new URL('./tomeCooldown.svg', import.meta.url).href,
	tomeAgility: new URL('./tomeAgility.svg', import.meta.url).href,
	tomeVitality: new URL('./tomeVitality.svg', import.meta.url).href,
	tomeArmor: new URL('./tomeArmor.svg', import.meta.url).href,
	tomeBlood: new URL('./tomeBlood.svg', import.meta.url).href,
	tomeRange: new URL('./tomeRange.svg', import.meta.url).href,
	tomeSize: new URL('./tomeSize.svg', import.meta.url).href,
	tomeDuration: new URL('./tomeDuration.svg', import.meta.url).href,
	tomeQuantity: new URL('./tomeQuantity.svg', import.meta.url).href,
	tomeFortune: new URL('./tomeFortune.svg', import.meta.url).href,
	weaponAura: new URL('./weaponAura.svg', import.meta.url).href,
	weaponSword: new URL('./weaponSword.svg', import.meta.url).href,
	weaponAxe: new URL('./weaponAxe.svg', import.meta.url).href,
	weaponStaff: new URL('./weaponStaff.svg', import.meta.url).href,
	weaponBow: new URL('./weaponBow.svg', import.meta.url).href,
};
